config/routes.rb
Crowdfunder::Application.routes.draw do

  root :to => "welcome#index"

  match "logout" => "sessions#destroy", :as => "logout"
  resources :projects do
    resources :pledges, :only => [:new, :create]
  end
  resources :users, :except => :index

  resources :sessions, :except => [:show, :update, :destroy]

  namespace :my do 
    resources :projects do
      resources :images
    end
  end

 

end

app/models/image.rb
class Image < ActiveRecord::Base
  	attr_accessible :file 
 	belongs_to :project 


	mount_uploader :file, ImageUploader

	validates :project, presence: true
	validates :file, presence: true
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  attr_accessible :amount, :project_id, :user_id
  belongs_to :user
  belongs_to :project

  validates_presence_of :user
  validates_presence_of :project
  validates :amount, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :pledges
	has_many :images, dependent: :destroy
	has_many :supporters, :through => :pledges, :source => :user
  	attr_accessible :description, :goal, :teaser, :title, :user_id

  	validates :title, presence: true, length: {maximum: 100}
  	validates :teaser, presence: true, length: {maximum: 255}
  	validates :description, presence: true
  	validates :goal, presence: true, numericality: {greater_than: 0, allow_blank: true}

  def raised
    self.pledges.sum(:amount)
  end

  def percent_raised
    ((raised.to_f / goal) * 100).to_i
  end

  def succeeded?
    percent_raised >= 100
  end

  def surpassed_goal?
    percent_raised > 100
  end

  def number_of_supporters
    self.supporters.uniq.count # if you make two pledges, you are still one supporter
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body
  attr_accessible :first_name, :last_name, :email, :password
  has_many :projects
  has_many :pledges
  
  validates_presence_of :password, :on => :create
  validates_presence_of :first_name, :on => :create
  validates_presence_of :last_name, :on => :create
  validates_presence_of :email, :on => :create

  def name
  	first_name + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :nav_state

  protected

  # Sorcery automatically looks for a method called not_authenticated  
  def not_authenticated
    redirect_to new_session_path, :alert => "Please login first."
  end

  def nav_state
    # To be overwritten by controllers
  end
end

app/controllers/my/images_controller.rb
class My::ImagesController < ApplicationController
  before_filter :require_login
  before_filter :require_project

  def index
    @images = @project.images.order(:id)
    @image = @project.images.build
  end

  def create
    @image = @project.images.build params[:image]
    if @image.save
      redirect_to [:my, @project, :images], notice: "Image uploaded. Check it out below."
    else
      @images = @project.images.order(:id)
      render :index
    end
  end

  protected

  def require_project
    @project = current_user.projects.find params[:project_id]
  end

  def nav_state
    @nav = :my_projects
  end
end

app/controllers/my/projects_controller.rb
class My::ProjectsController < ApplicationController

  before_filter :require_login
  before_filter :require_project, except: [:index, :new, :create]


  def index
    @projects = current_user.projects.order('projects.created_at DESC').all
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def update
    if @project.update_attributes params[:project]
      redirect_to [:my, :projects], notice: "Project updated!"
    else
      render :edit
    end
  end

  def create
    @project = current_user.projects.build params[:project]
    if @project.save
      redirect_to [:my, :projects], notice: "Project created!"
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to my_projects_path, :notice => "deleted"
  end

  def nav_state
    @nav = :my_projects
  end

  protected

  def require_project
    @project = current_user.projects.find params[:id]
  end

  

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  before_filter :require_login
  before_filter :require_project

  def new
    @pledge = @project.pledges.build
  end

  def create
    @pledge = @project.pledges.build params[:pledge]
    @pledge.user = current_user

    if @pledge.save
      UserMailer.new_pledge(@pledge).deliver #will now send emails when a pledge is created
      redirect_to @project, notice: "Nice! Thanks for pledging $#{@pledge.amount} for this project."
    else
      render :new
    end
  end

  protected

  def require_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.order('projects.created_at DESC').page(params[:page])
	end

	def show
		@project = Project.find(params[:id])
	end

	def edit

	end


	
	def nav_state
    	@nav = :projects
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = login(params[:email], params[:password]) 
	    if @user
	      redirect_back_or_to root_url, :notice => "Logged in!"  
	    else  
	      flash[:notice] = "Invalid"  
	      render "new"
	    end  
	end

	def destroy
		logout
		redirect_to root_url, :notice => "Bye"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])

		if @user.save
			auto_login(@user)
  			flash[:success] = "Account created"
  			redirect_to root_url, :notice => "Account created"
		else
			render "new"
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	
	
	def nav_state
    	@nav = :home
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my/images_helper.rb
module My::ImagesHelper
end

app/helpers/my/projects_helper.rb
module My::ProjectsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if flash[:notice] %>
	 	<p><%= flash[:notice] %></p>
	<%end%>
	<% if flash[:alert] %>
	 	<p><%= flash[:alert] %></p>
	<%end%>

	<%= render 'layouts/shared/nav' %>



    <div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/shared/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">CrowdFunder</a>
      <div class="nav-collapse collapse">
        <ul class="nav">

        

        <li class="<%= 'active' if @nav == :home %>">
          <%= link_to 'Home', :root %>
        </li>
        <li class="<%= 'active' if @nav == :projects %>">
          <%= link_to 'Projects', :projects %>
        </li>
        <% if logged_in? %>
          <li class="divider-vertical"></li>
          <li class="<%= 'active' if @nav == :my_projects %>">
            <%= link_to 'My Projects', [:my, :projects] %>
          </li>
        <% end %>
        
        </ul>

          <div class="pull-right">
            <% if logged_in? %>
              <%= link_to 'Logout', logout_path, class: 'btn' %>
            <% else %>
              <%= link_to 'Sign Up', [:new, :user], class: 'btn btn-primary' %>
            <% end %>
          </div>
          
    </div>
  </div>
</div>

app/views/my/images/index.html.erb
<p>
<%= form_for([:my, @project, @image]) do |f| %>

  <% if @image.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</p>
	<%= f.file_field :file %>
	<%= f.submit "Upload Image" %>
<% end %>

<% @images.each do |image| %>
	<div class = "image"> 
		<img src= "<%= image.file %>" />		
	</div>
<% end %>

app/views/my/projects/edit.html.erb
<%= form_for [:my, @project] do |f| %>

	<%= f.label "Title"%> 
	<%= f.text_field :title, {placeholder: 'Title'} %>

	<%= f.label "Teaser"%> 
	<%= f.text_field :teaser, {placeholder: 'teaser'} %>

	<%= f.label "Description"%> 
	<%= f.text_field :description, {placeholder: 'description'} %>

	<%= f.label "Goal"%> 
	<%= f.text_field :goal, {placeholder: 'goal'} %>

	<div class="actions"><%=submit_tag 'Update Project' %></div>
	

<% end %>

	<%= link_to 'Manage Images', my_project_images_path(@project) %>
	<%= link_to 'Delete', my_project_path(@project), :confirm => 'Are you sure you want to delete this project?', :method => :delete %>

app/views/my/projects/index.html.erb
<h1>Projects</h1>


<% @projects.each do |project| %>

<div class="project">
	<%=project.title%>
	<%=project.teaser%>
	<%=project.description%>
	<%=project.goal%>
</div>

<%= link_to "Update Project", edit_my_project_path(project) %>



<% end %>

<%= link_to "New Project", new_my_project_path %>

app/views/my/projects/new.html.erb
<%= form_for [:my, @project] do |f| %>

	<%= f.label "Title"%> 
	<%= f.text_field :title, {placeholder: 'Title'} %>

	<%= f.label "Teaser"%> 
	<%= f.text_field :teaser, {placeholder: 'teaser'} %>

	<%= f.label "Description"%> 
	<%= f.text_field :description, {placeholder: 'description'} %>

	<%= f.label "Goal"%> 
	<%= f.number_field :goal, {placeholder: 'goal'} %>

	<div class="actions"><%=submit_tag 'Publish Project' %></div>
	
<% end %>

app/views/pledges/new.html.erb
<%= form_for [@project, @pledge] do |f| %>

  

        <div class="field"> 
           		<%= f.number_field :amount, {placeholder: 'amount'} %>
        </div> 
       
        <div class="actions-bigger-btn"><%=submit_tag 'Pledge Now' %></div>
       
<% end %>

app/views/projects/_displayProjects.html.erb
<% @projects.each do |project| %>
	
	<%= render 'project', :project => project %>
<% end %>

<%= paginate @projects %>

app/views/projects/_project.html.erb
<li class="project">
  <%= link_to project.title, project %>
  <br />
  <p>
    <%= project.teaser %>
  </p>
</li>

app/views/projects/index.html.erb
Listing projects

<%= render 'displayProjects' %>

app/views/projects/show.html.erb
<h1><%= link_to @project[:title], @project %></h1>


		<li class=""><a>Projects<a>
		</li>
	

	
   	<p> <%= link_to "Back This Project", new_project_pledge_path(@project)%> </p>
 

app/views/users/new.html.erb
<%= form_for @user do |f| %>

        <% unless f.object.errors.empty? %>
          <div class="alert alert-error">
            <strong>Try again after fixing the following things:</strong><br/>
            <ul>
              <% f.object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field"> 
           		<%= f.text_field :first_name, {placeholder: 'First Name'} %>
        </div> 
         <div class="field"> 
              <%= f.text_field :last_name, {placeholder: 'Last Name'} %>
        </div> 
        <div class="field">
  				<%= f.text_field :email, {placeholder: 'Email'} %>
  			</div>
        
  
  			<div class="field">
   			  <%= f.password_field :password, {placeholder: 'Password'}%>
  		  </div>
       

       <div class="actions-bigger-btn"><%=submit_tag 'Create Account' %></div>
       
<% end %>